---
title: "4T1-scRNA-Parsev3DropSeq-HarmonyIntegration"
author: "Ian Schrack"
date: "2025-01-13"
output: html_document
---

READ ME
Add a description of what this file does later. 


```{r Load necessary libraries}
library(harmony)
library(Seurat)
library(SeuratDisk)
library(SeuratWrappers) # after a ton of frustration, I had to install.packages("R.utils")
```


```{r Load & prepare the pre-compiled datasets}
# These are the Parse V3 scRNA datasets
AllTissue <- readRDS("/Users/ianschrack/Documents/GitHub/4T1-Neutrophil-Parse-scRNAseq-Paper/Data/AllTissue_ParseV3.rds")
AllTissue$dataset <- "Parse"

# These are the DropSeq datasets assembled by Sophia
load("/Users/ianschrack/Documents/GitHub/4T1-Neutrophil-Parse-scRNAseq-Paper/Data/Spleen_DropSeq.robj")
load("/Users/ianschrack/Documents/GitHub/4T1-Neutrophil-Parse-scRNAseq-Paper/Data/Lung_DropSeq.robj")
load("/Users/ianschrack/Documents/GitHub/4T1-Neutrophil-Parse-scRNAseq-Paper/Data/Scaffold_DropSeq.robj")

# Use native merge functions to compile a full DropSeq object
Dropseq <- merge(lung, y = c(scaf, spleen))
Dropseq$dataset <- "Dropseq"

# Use native merge function to compile a DropSeq & Parse merged object
AllTissue <- merge(AllTissue, y = Dropseq)
```

```{r Pre-Filtering}
VlnPlot(AllTissue, pt.size = 0, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
FeatureScatter(AllTissue, feature1 = "nCount_RNA", feature2 = "percent.mt")
FeatureScatter(AllTissue, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
```

```{r Clean up meta data}
AllTissue@meta.data$Tissue[AllTissue@meta.data$Tissue == "lung"] <- "Lung"
AllTissue@meta.data$Tissue[AllTissue@meta.data$Tissue == "scaffold"] <- "Scaffold"
AllTissue@meta.data$Tissue[AllTissue@meta.data$Tissue == "spleen"] <- "Spleen"

AllTissue@meta.data$Day[AllTissue@meta.data$Time == "0"] <- "D0"
AllTissue@meta.data$Day[AllTissue@meta.data$Time == "7"] <- "D7"
AllTissue@meta.data$Day[AllTissue@meta.data$Time == "14"] <- "D14"
AllTissue@meta.data$Day[AllTissue@meta.data$Time == "21"] <- "D21"
AllTissue@meta.data$Time <- NULL

AllTissue@meta.data$Replicate[AllTissue@meta.data$dataset == "Dropseq"] <- "R5"

AllTissue@meta.data$Experiment <- NULL
AllTissue@meta.data$basic <- NULL
AllTissue@meta.data$EVERYTHING <- NULL
AllTissue@meta.data$phenotype <- NULL
```


```{r Cell counts}
print("Lung Pre-Filter")
temp <- subset(AllTissue, subset = Tissue == "Lung")
addmargins(table(temp@meta.data$Replicate, temp@meta.data$Day))

print("Scaffold Pre-Filter")
temp <- subset(AllTissue, subset = Tissue == "Scaffold")
addmargins(table(temp@meta.data$Replicate, temp@meta.data$Day))

print("Blood Pre-Filter")
temp <- subset(AllTissue, subset = Tissue == "Blood")
addmargins(table(temp@meta.data$Replicate, temp@meta.data$Day))
```

```{r}
# Perform the filtering (Seurat uses nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5))
AllTissue <- subset(AllTissue, subset = nFeature_RNA < 5000 & nCount_RNA < 20000 & percent.mt < 15)

Layers(AllTissue)
# "data.1"       "data.2"       "counts.1"     "scale.data.1" "counts.2"  

# Layers were split so we need to join them
AllTissue <- JoinLayers(AllTissue)

# Keep just the counts and data layers
Layers(AllTissue)
AllTissue[["RNA"]]$scale.data.1 <- NULL
AllTissue[["RNA"]]$scale.data <- NULL
Layers(AllTissue)

# Split layers based on sequencing technology
AllTissue[["RNA"]] <- split(AllTissue[["RNA"]], f = AllTissue$dataset)

options(future.globals.maxSize = 8000*1024^2)
future::plan("multisession", workers = 4) # do parallel
AllTissue <- NormalizeData(AllTissue, normalization.method = "LogNormalize", scale.factor = 10000)
AllTissue <- FindVariableFeatures(AllTissue, selection.method = "vst", nfeatures = 2000)
AllTissue <- ScaleData(AllTissue)
AllTissue <- RunPCA(AllTissue)

AllTissue <- FindNeighbors(AllTissue, dims = 1:40)
AllTissue <- FindClusters(AllTissue, resolution = 0.5, cluster.name  = "unintegrated_clusters")
AllTissue <- RunUMAP(AllTissue, dims = 1:40, reduction.name = "umap.unintegrated")

DimPlot(AllTissue, reduction = "umap.unintegrated", label = TRUE)
DimPlot(AllTissue, reduction = "umap.unintegrated", group.by = "dataset")
```


```{r Integrate the data}
# Set the globals to make processing quicker
options(future.globals.maxSize = 24000*1024^2)
future::plan("multisession", workers = 8) # do parallel

# Run Harmony-based integration
AllTissue <- RunHarmony(AllTissue, c("dataset", "Tissue", "Day"))

AllTissue[["RNA"]] <- JoinLayers(AllTissue[["RNA"]])
```

```{r Save integrated dataset}
saveRDS(AllTissue, 
        file = "/Users/ianschrack/Documents/GitHub/4T1-Neutrophil-Parse-scRNAseq-Paper/Data/ParseDropSeqHarmonyDatasetIntegrate_PreAnnotate.rds")
```

```{r Verify integrated dataset}
AllTissue <- FindNeighbors(AllTissue, reduction = "harmony", dims = 1:40, verbose = FALSE)
AllTissue <- FindClusters(AllTissue, resolution = 1, verbose = FALSE, algorithm = 2, method = "igraph")
AllTissue <- RunUMAP(AllTissue, dims = 1:40, reduction = "harmony", verbose = FALSE, min.dist = 0.5, spread = 0.5)

DimPlot(AllTissue, reduction = "umap", group.by = "dataset")
```

